name: magic
description: "Technical Test - Alfredo Paez"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  http: ^1.2.2
  injectable: ^2.4.2
  get_it: ^7.7.0
  flutter_screenutil: ^5.9.3
  skeletonizer: ^1.4.2
  go_router: ^14.2.7
  cached_network_image: ^3.4.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
